/* Generated By:JavaCC: Do not edit this line. ParseCpslConstants.java */
package gate.jape.parser;

public interface ParseCpslConstants {

  int EOF = 0;
  int space = 1;
  int spaces = 2;
  int newline = 3;
  int digits = 4;
  int letter = 5;
  int letterOrUnderscore = 6;
  int letters = 7;
  int lettersAndDigits = 8;
  int letterOrDigitOrDash = 9;
  int lettersAndDigitsAndDashes = 10;
  int multiphase = 11;
  int phases = 12;
  int path = 13;
  int phasesWhiteSpace = 14;
  int phasesSingleLineCStyleComment = 15;
  int phasesSingleLineCpslStyleComment = 16;
  int phasesCommentStart = 17;
  int phasesCommentChars = 18;
  int phasesCommentEnd = 19;
  int javaimport = 20;
  int controllerstarted = 21;
  int controllerfinished = 22;
  int controlleraborted = 23;
  int phase = 24;
  int input = 25;
  int option = 26;
  int rule = 27;
  int macro = 28;
  int template = 29;
  int priority = 30;
  int pling = 31;
  int kleeneOp = 32;
  int attrOp = 33;
  int metaPropOp = 34;
  int integer = 35;
  int string = 47;
  int bool = 48;
  int ident = 49;
  int floatingPoint = 50;
  int exponent = 51;
  int colon = 52;
  int semicolon = 53;
  int period = 54;
  int bar = 55;
  int comma = 56;
  int leftBrace = 57;
  int rightBrace = 58;
  int leftBracket = 59;
  int rightBracket = 60;
  int leftSquare = 61;
  int rightSquare = 62;
  int assign = 63;
  int colonplus = 64;
  int whiteSpace = 65;
  int singleLineCStyleComment = 66;
  int singleLineCpslStyleComment = 67;
  int commentStart = 68;
  int commentChars = 69;
  int commentEnd = 70;
  int other = 71;

  int DEFAULT = 0;
  int IN_PHASES = 1;
  int PHASES_WITHIN_COMMENT = 2;
  int IN_STRING = 3;
  int WITHIN_COMMENT = 4;

  String[] tokenImage = {
    "<EOF>",
    "<space>",
    "<spaces>",
    "<newline>",
    "<digits>",
    "<letter>",
    "<letterOrUnderscore>",
    "<letters>",
    "<lettersAndDigits>",
    "<letterOrDigitOrDash>",
    "<lettersAndDigitsAndDashes>",
    "\"Multiphase:\"",
    "\"Phases:\"",
    "<path>",
    "<phasesWhiteSpace>",
    "<phasesSingleLineCStyleComment>",
    "<phasesSingleLineCpslStyleComment>",
    "<phasesCommentStart>",
    "<phasesCommentChars>",
    "<phasesCommentEnd>",
    "\"Imports:\"",
    "\"ControllerStarted:\"",
    "\"ControllerFinished:\"",
    "\"ControllerAborted:\"",
    "\"Phase:\"",
    "\"Input:\"",
    "\"Options:\"",
    "\"Rule:\"",
    "\"Macro:\"",
    "\"Template:\"",
    "\"Priority:\"",
    "\"!\"",
    "<kleeneOp>",
    "<attrOp>",
    "\"@\"",
    "<integer>",
    "\"\\\"\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\t\"",
    "\"\\\\b\"",
    "\"\\\\f\"",
    "\"\\\\\\\"\"",
    "\"\\\\\\\'\"",
    "\"\\\\\\\\\"",
    "<token of kind 45>",
    "<token of kind 46>",
    "\"\\\"\"",
    "<bool>",
    "<ident>",
    "<floatingPoint>",
    "<exponent>",
    "\":\"",
    "\";\"",
    "\".\"",
    "\"|\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\":+\"",
    "<whiteSpace>",
    "<singleLineCStyleComment>",
    "<singleLineCpslStyleComment>",
    "<commentStart>",
    "<commentChars>",
    "<commentEnd>",
    "<other>",
    "\"-->\"",
  };

}
