/* Generated By:JavaCC: Do not edit this line. ParseCpslConstants.java */
package gate.jape.parser;

public interface ParseCpslConstants {

  int EOF = 0;
  int space = 1;
  int spaces = 2;
  int newline = 3;
  int digits = 4;
  int letter = 5;
  int letters = 6;
  int lettersAndDigits = 7;
  int letterOrDigitOrDash = 8;
  int lettersAndDigitsAndDashes = 9;
  int multiphase = 10;
  int phases = 11;
  int path = 12;
  int phasesWhiteSpace = 13;
  int phasesSingleLineCStyleComment = 14;
  int phasesSingleLineCpslStyleComment = 15;
  int phasesCommentStart = 16;
  int phasesCommentChars = 17;
  int phasesCommentEnd = 18;
  int phase = 19;
  int input = 20;
  int option = 21;
  int rule = 22;
  int macro = 23;
  int priority = 24;
  int pling = 25;
  int kleeneOp = 26;
  int integer = 27;
  int string = 34;
  int bool = 35;
  int ident = 36;
  int floatingPoint = 37;
  int exponent = 38;
  int colon = 39;
  int semicolon = 40;
  int period = 41;
  int bar = 42;
  int comma = 43;
  int leftBrace = 44;
  int rightBrace = 45;
  int leftBracket = 46;
  int rightBracket = 47;
  int assign = 48;
  int equals = 49;
  int colonplus = 50;
  int whiteSpace = 51;
  int singleLineCStyleComment = 52;
  int singleLineCpslStyleComment = 53;
  int commentStart = 54;
  int commentChars = 55;
  int commentEnd = 56;
  int other = 57;

  int DEFAULT = 0;
  int IN_PHASES = 1;
  int PHASES_WITHIN_COMMENT = 2;
  int IN_STRING = 3;
  int WITHIN_COMMENT = 4;

  String[] tokenImage = {
    "<EOF>",
    "<space>",
    "<spaces>",
    "<newline>",
    "<digits>",
    "<letter>",
    "<letters>",
    "<lettersAndDigits>",
    "<letterOrDigitOrDash>",
    "<lettersAndDigitsAndDashes>",
    "\"Multiphase:\"",
    "\"Phases:\"",
    "<path>",
    "<phasesWhiteSpace>",
    "<phasesSingleLineCStyleComment>",
    "<phasesSingleLineCpslStyleComment>",
    "<phasesCommentStart>",
    "<phasesCommentChars>",
    "<phasesCommentEnd>",
    "\"Phase:\"",
    "\"Input:\"",
    "\"Options:\"",
    "\"Rule:\"",
    "\"Macro:\"",
    "\"Priority:\"",
    "\"!\"",
    "<kleeneOp>",
    "<integer>",
    "\"\\\"\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\t\"",
    "\"\\\\\\\"\"",
    "<token of kind 33>",
    "\"\\\"\"",
    "<bool>",
    "<ident>",
    "<floatingPoint>",
    "<exponent>",
    "\":\"",
    "\";\"",
    "\".\"",
    "\"|\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"==\"",
    "\":+\"",
    "<whiteSpace>",
    "<singleLineCStyleComment>",
    "<singleLineCpslStyleComment>",
    "<commentStart>",
    "<commentChars>",
    "<commentEnd>",
    "<other>",
    "\"-->\"",
  };

}
